plugins {
    id 'com.android.application'
}

android {
    namespace 'io.github.asteroidb612zs.hondatadash'
    compileSdk 33

    defaultConfig {
        applicationId "io.github.asteroidb612zs.hondatadash"
        minSdk 17
        targetSdk 28
        versionCode 56
        versionName "2.1.1-stability.1"
    }

    lintOptions {
        abortOnError false
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.debug
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

dependencies {
    // 零依赖 — 纯 Android Framework API
}
